name: Evaluate PR with GPT

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  evaluate-pr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch PR details
        id: pr_info
        run: |
          echo "PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
      - name: Run PR Evaluation Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MONDAY_API_KEY: ${{ secrets.MONDAY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash ci-scripts/evaluate_pr.sh "$GITHUB_ENV"
